apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  labels:
    app: metrics-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
      - name: metrics-collector
        image: metrics-collector:latest  # Use your Docker image (ensure it's tagged/pushed correctly)
        ports:
        - containerPort: 5555