apiVersion: v1
kind: Service
metadata:
  name: metrics-collector-service
  labels:
    app: metrics-collector
spec:
  type: ClusterIP  # Use LoadBalancer or NodePort for external access if needed
  ports:
  - port: 5555
    targetPort: 5555
  selector:
    app: metrics-collector